### ISSUE TITLE
求助，希望回复

### ISSUE THREAD

**Issue by fengfeng420** [YtengTan/ytengtan.github.io#1]
您好，我看到您之前在Unified Adversarial Patch for Cross-modal Attacks in the Physical World这篇内容中发表了一些看法，想跟你交流下一些问题，诚挚的希望您能给予回复。ps：做毕设的本科生，走投无路了，实在抱歉。

**Comment by YtengTan** [comment]
你好 可以加微信聊：find_tan

**Comment by fengfeng420** [comment]
> 你好 可以加微信聊：find_tan

太感谢了，我加您了
